### PR TITLE
fix when multipolygon composed of two polygons of opposite clockwise

### PR DESCRIPTION
**Pull request by xlqian**
fix issue: https://github.com/georust/rust-geo/issues/92

### CODE REVIEW

**Comment by xlqian** [comment]
https://github.com/georust/rust-geo/issues/92

**Comment by frewsxcv** [comment]
Thanks!

**Comment by xlqian** [comment]
@frewsxcv you're welcome!

**Comment by frewsxcv** [comment]
I'll try to get a release out for this sometime today

**Pull request merged**
