### PR TITLE
Add generic trait impl for RotatePoint.

### PR DESCRIPTION
**Pull request by frewsxcv**
Originally added in https://github.com/georust/rust-geo/pull/151, but
extracted out due to indecision about how to move forward with Rotate.

### CODE REVIEW

**Comment by urschrei** [comment]
I can't think of a good way to unify this, short of splitting the Centroid trait into `CentroidWeighted` and `CentroidUnweighted` or similar. I don't think it would cause confusion, but it's certainly less simple than the current approach.

**Comment by frewsxcv** [comment]
@urschrei You're talking about `Rotate` (not `RotatePoint`) right? This PR doesn't change the centroid or rotation behavior

**Comment by urschrei** [comment]
@frewsxcv Yep, sorry, should probably just have left it as a comment on #151.

**Pull request merged**
