### PR TITLE
Utilize `hypot` method.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by urschrei** [comment]
I think my first-ever PR to Geo was a fix for this usage in the Distance module, and now I learn that I'm guilty of the same thing 😔

**Comment by frewsxcv** [comment]
https://github.com/georust/rust-geo/pull/53 👋

**Comment by urschrei** [comment]
Like sands through the ⏳…

**Comment by frewsxcv** [comment]
bors r=TeXitoi

**Pull request merged**
