### PR TITLE
fix polygon centroid for flat polygon

### PR DESCRIPTION
**Pull request by antoine-de**
if the polygon is flat (area = 0), it is considered as a linestring for the centroid computation.

without this for a flat polygon eg:

A ----> B -----> C
^-------------------|

the centroid was `Some(NaN, NaN)`

without this, the test `empty_interior_polygon_test` was also causing a `panic!` because of the unwrap in the centroid method.

### CODE REVIEW

**Comment by urschrei** [comment]
Good catch. Thank you!

**Comment by urschrei** [comment]
bors r=urschrei

**Comment by antoine-de** [comment]
great, thanks!

when do you think this will be released?

**Comment by urschrei** [comment]
@antoine-de released to crates.io as `0.8.1`

**Comment by antoine-de** [comment]
thanks 👍

**Pull request merged**
