### PR TITLE
Add basic Point methods

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds some basic methods to the `Point` type. This includes an XY constructor, getters and setters for x, y, lat and lng and implementations for the `Add`, `Sub`, `Neg` traits.

All methods are documented and include examples that are runnable as doctests.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks, this is great!

**Comment by Turbo87** [comment]
one thing where I'm not entirely sure is: do we prefer immutable methods that create new instances for mutations or is it prefered to mutate the actual object? I guess since we support `clone()` and Rust is pretty good in preventing unintentional mutation we should prefer the in-place mutation, right?

**Comment by frewsxcv** [comment]
That's something that I was undecided about when I thought about it last. I'm still undecided, but there's no reason to hold us back since we changing our decision in the future won't be too bad hopefully.

**Comment by Turbo87** [comment]
okay, agreed. Just FYI I'm not really fluent in Rust yet so it would be great if my pull requests could be thoroughly reviewed.

**Pull request merged**
